//
//  StyleKit.h
//  Stunts App
//
//  Created by Rich Allen on May 15, 2018.
//  Copyright © 2018 12 South Creative. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface StyleKit : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger {
    StyleKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    StyleKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    StyleKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    StyleKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
} StyleKitResizingBehavior;

extern CGRect StyleKitResizingBehaviorApply(StyleKitResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! All Views
+ (void)drawSignUp;
+ (void)drawSignUpWithFrame:(CGRect)targetFrame resizing:(StyleKitResizingBehavior)resizing;
+ (void)drawSignIn;
+ (void)drawSignInWithFrame:(CGRect)targetFrame resizing:(StyleKitResizingBehavior)resizing;
+ (void)drawHome;
+ (void)drawHomeWithFrame:(CGRect)targetFrame resizing:(StyleKitResizingBehavior)resizing;
+ (void)drawWelcome;
+ (void)drawWelcomeWithFrame:(CGRect)targetFrame resizing:(StyleKitResizingBehavior)resizing;
+ (void)drawMembers;
+ (void)drawMembersWithFrame:(CGRect)targetFrame resizing:(StyleKitResizingBehavior)resizing;
+ (void)drawProfileAbout;
+ (void)drawProfileAboutWithFrame:(CGRect)targetFrame resizing:(StyleKitResizingBehavior)resizing;
+ (void)drawProfile1Credits;
+ (void)drawProfile1CreditsWithFrame:(CGRect)targetFrame resizing:(StyleKitResizingBehavior)resizing;
+ (void)drawProfile1Skills;
+ (void)drawProfile1SkillsWithFrame:(CGRect)targetFrame resizing:(StyleKitResizingBehavior)resizing;


#pragma mark - Canvas Images

//! All Views
+ (UIImage *)imageOfSignUp;
+ (UIImage *)imageOfSignIn;
+ (UIImage *)imageOfHome;
+ (UIImage *)imageOfWelcome;
+ (UIImage *)imageOfMembers;
+ (UIImage *)imageOfProfileAbout;
+ (UIImage *)imageOfProfile1Credits;
+ (UIImage *)imageOfProfile1Skills;


@end
